# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: gradlew build

on: [ workflow_dispatch ]

jobs:
  build:
    name: Gradle ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: KengoTODA/setup-java@update-ncc-3rd
      with:
        distribution: adopt
        java-version: 8
    - name: Build datastore-todo
      run: |
          cd datastore-todo
          chmod +x gradlew
          ./gradlew build --no-daemon
    - name: Build datastore-blog
      run: |
          cd datastore-blog
          chmod +x gradlew
          ./gradlew build --no-daemon

    - name: Build auth-hostedui
      run: |
          cd auth-hostedui
          chmod +x gradlew
          ./gradlew build --no-daemon


