# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: gradlew build

on: [ workflow_dispatch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: KengoTODA/setup-java@introduce-cache
      with:
        distribution: adopt
        java-version: 1.8
        cache: gradle
    - name: Build datastore-todo
      run: |
          cd datastore-todo
          chmod +x gradlew
          ./gradlew build
    - name: Build datastore-blog
      run: |
          cd datastore-blog
          chmod +x gradlew
          ./gradlew build

    - name: Build auth-hostedui
      run: |
          cd auth-hostedui
          chmod +x gradlew
          ./gradlew build


